name: Java CI/CD Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean install -DskipTests
          
      # - name: Sonarqube analysis
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      #   run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=java-starter -Dsonar.projectName='java-starter'



      # - name: Run Unit Tests
      #   run: mvn test

      # - name: Static Code Analysis (SonarQube)
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: mvn sonar:sonar -Dsonar.projectKey=my-project -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

      - name: Package Artifact
        run: mvn package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: build Docker image
        run: |
         # IMAGE_NAME=$(basename $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
         docker build -t ghcr.io/Sunaina0510/Java/java-app:${{ github.sha }} .




      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/java-app:${{ github.sha }}

  # deploy:
  #   name: Deploy to Dev Environment
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Download Artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: java-app

  #     - name: Deploy to Dev Server
  #       run: |
  #         echo "Deploying to Dev Environment..."
  #         # scp or use another deployment mechanism

  # approve_and_deploy_prod:
  #   name: Deploy to Production (Manual Approval)
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Wait for Manual Approval
  #       uses: hmarr/auto-approve-action@v3
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Deploy to Production
  #       run: echo "Deploying to Production..."
